| makeresults count=5 
| streamstats count as id 
| eval size=case(id<5, 500, id=5, 9500000) 
| eval _raw="10.0.0.5 - - [" . strftime(now(), "%d/%b/%Y:%H:%M:%S") . "] \"GET /export_users HTTP/1.1\" 200 " . size 
| collect index=main
